### ISSUE TITLE
Hellp

### ISSUE THREAD

**Issue by tsoulii** [MaDHouSe79/mh-trailers#1]
Hi sir
I have a problem, please. I am using a custom car key You really added it 
But the key gives me a different car number than the one that was taken out
I don't know how to get him to take the truck out randomly like he usually does

use qs-vehiclekeys

Thank you if you want to help me

``` 
local model = GetDisplayNameFromVehicleModel(GetEntityModel(vehicle))
local plate = GetVehicleNumberPlateText(vehicle)
exports['qs-vehiclekeys']:GiveKeys(plate, model)

**Comment by MaDHouSe79** [comment]
Hi, yes i can help you, you need to edit this 2 lines.

https://github.com/MaDHouSe79/mh-trailers/blob/fd8ef44b854571ca7bae41d4dd1879ecb78fce36/client/main.lua#L106
https://github.com/MaDHouSe79/mh-trailers/blob/fd8ef44b854571ca7bae41d4dd1879ecb78fce36/client/main.lua#L107

or change the hole function below or you add it where i add it (in de client/main.lua file):

```lua
local function spawnTruck(truckModel, position, heading)
    QBCore.Functions.SpawnVehicle(truckModel, function(veh)
        currentTruck = veh
        currentTruckPlate = 'T_RT_' .. string.format('%06d', math.random(100, 999))
        SetVehicleNumberPlateText(currentTruck, currentTruckPlate)
        SetEntityHeading(currentTruck, heading)
        SetFuel(currentTruck, 100.0)
        SetVehicleOnGroundProperly(currentTruck)
        TaskWarpPedIntoVehicle(PlayerPedId(), currentTruck, -1)
        SetVehicleCustomPrimaryColour(loading, 0, 0, 0)
        SetVehicleDirtLevel(currentTruck, 0)
        WashDecalsFromVehicle(currentTruck, 1.0)
        SetVehRadioStation(currentTruck, 'OFF')
        SetVehicleEngineHealth(currentTruck, 1000.0)
        SetVehicleBodyHealth(currentTruck, 1000.0)

        -- add here 
        local model = GetDisplayNameFromVehicleModel(GetEntityModel(currentTruck))  
        local plate = GetVehicleNumberPlateText(currentTruck)
        exports['qs-vehiclekeys']:GiveKeys(plate, model)

        -- remove this 2 here below
        TriggerServerEvent("qb-vehiclekeys:server:AcquireVehicleKeys", QBCore.Functions.GetPlate(currentTruck)) --< to remove
        TriggerEvent('mh-vehiclekeyitem:client:CreateTempKey', currentTruck) --< to remove

    end, position, true)
end
```
Greets MaDHouSe.

**Comment by tsoulii** [comment]
Yes, this is almost what I did, but it does not work for me, and this is the only thing that I found difficult to modify because of the number plate that was modified.

![image](https://github.com/MaDHouSe79/mh-trailers/assets/34017026/e59193ee-fe8b-4b8e-9c66-b7dc976c5d1b)

**Comment by tsoulii** [comment]
Thank you very much. It worked for me and it works perfectly :smiling_face_with_3_hearts: 
I know that I am gone and always come back looking for you :blush: 
It just needs to remove the key too

```local model = GetDisplayNameFromVehicleModel(GetEntityModel(vehicle))
local plate = GetVehicleNumberPlateText(vehicle)
exports['qs-vehiclekeys']:RemoveKeys(plate, model)```

**Comment by MaDHouSe79** [comment]
you can replase the function Park to this fiunction

```lua
local function Park()
    if IsPedInAnyVehicle(ped) then
        local veh = GetVehiclePedIsIn(ped, false)
        TaskLeaveVehicle(ped, veh)
        local model = GetDisplayNameFromVehicleModel(GetEntityModel(veh))
        local plate = GetVehicleNumberPlateText(veh)
        exports['qs-vehiclekeys']:GiveKeys(plate, model)
        Wait(1500)
        QBCore.Functions.DeleteVehicle(veh)
        DeleteEntity(GetVehiclePedIsIn(ped, false))
    end 
end
```

**Comment by tsoulii** [comment]
It didn't work for me I tried changing a lot of things it just doesn't seem to respond

But I thank you very much for what you have done and I hope you will update us because I still visit your account every day to find out what is new with you.

**Comment by MaDHouSe79** [comment]
if you bring back the truck to the trailer garage the vehicle despawn?

**Comment by tsoulii** [comment]
Yes, press E and then go down automatically and the truck and trailer are deleted

I put print to see if it was responding or not and nothing appeared. I even put it on every line and nothing appeared

**Comment by MaDHouSe79** [comment]
change this in client/main.lua
https://github.com/MaDHouSe79/mh-trailers/blob/f8c2ab8af8abefd9190e374dd4899c4ed1ff7b71/client/main.lua#L734

to 
```lua
RegisterNetEvent('qb-trailers:client:park', function()
    local ped = PlayerPedId()
    if currentTruck ~= nil then
        if IsPedInAnyVehicle(ped) then
            local vehicle = GetVehiclePedIsIn(ped, false)
            local plate = QBCore.Functions.GetPlate(vehicle)
            if currentTruck == vehicle then
                currentTruck = nil
                currentTruckPlate = nil
                TaskLeaveVehicle(ped, vehicle)
                local model = GetDisplayNameFromVehicleModel(GetEntityModel(vehicle))
                local plate = GetVehicleNumberPlateText(vehicle)
                exports['qs-vehiclekeys']:RemoveKeys(plate, model)
                Wait(1500)
                QBCore.Functions.DeleteVehicle(vehicle)
                DeleteEntity(vehicle)
            else
                QBCore.Functions.Notify(Lang:t('notify.return_wrong_vehicle'), "error")
            end
        end
    end
end)
```

**Comment by tsoulii** [comment]
Yes, it worked you are very magnificent 
Thank you for everything and thank you for giving some of your time to me. Thank you  ❤️❤️❤️❤️❤️

**Comment by MaDHouSe79** [comment]
You're welcome 😄
