### ISSUE TITLE
trailer

### ISSUE THREAD

**Issue by PanchoDaGoat** [MaDHouSe79/mh-trailers#2]
the big trailer i walk to where you walk and it doesnt turn blue but the small does....

**Comment by PanchoDaGoat** [comment]
the tr2 one doesnt have a target on it for some reason

**Comment by MaDHouSe79** [comment]
you need to add the tr2 trailer in qb shared/vehicles.lua, cause it uses that file to add a target on a vehicle.

hope tis fix your issue

**Comment by PanchoDaGoat** [comment]
ohhh alright thanks bro ima try it

**Comment by PanchoDaGoat** [comment]
its in the vehicles.lua now but it still doesnt show blue where you are in the video the tr2flat works and isnt in the vehicles.lua for some reason the pjtrailer i had to get the file for it to pop up but that doesnt turn blue either and its in the vehicles.lua as well.

**Comment by MaDHouSe79** [comment]
Can you try walking at the back of the trailer by the wheels and than look with target while looking at the wheels at the back? cause there is where is always do it.

**Comment by PanchoDaGoat** [comment]
yeah ill try now and the gooseneck doesnt work for me only the trflat does but then i took the cars off it and my truck got collided with the trflat2 as well

**Comment by PanchoDaGoat** [comment]
nothin on back of the tr2 or pj

**Comment by PanchoDaGoat** [comment]
[mh-hunters-main] Check for script update FAILED
[    c-scripting-core] InvokeNative: execution failed: Argument at index 1 was null.
[script:mh-hunters-ma] SCRIPT ERROR: Execution of native 000000002f7a49e6 in script host failed: Argument at index 1 was null.
[script:mh-hunters-ma] > [global chunk] (TriggerClientEventInternal.lua:3)
[script:mh-hunters-ma] > handler (@mh-hunters-main/server/main.lua:57)


this what i get for the hunters script

**Comment by MaDHouSe79** [comment]
Then i don't know why target does not work, on my end it works fine, no issues, only thing is that i have to look at the backwheels of the railer, sometime little left or right but it wil show up, atleast in my end it does :)

> [mh-hunters-main] Check for script update FAILED [ c-scripting-core] InvokeNative: execution failed: Argument at index 1 was null. [script:mh-hunters-ma] SCRIPT ERROR: Execution of native 000000002f7a49e6 in script host failed: Argument at index 1 was null. [script:mh-hunters-ma] > [global chunk] (TriggerClientEventInternal.lua:3) [script:mh-hunters-ma] > handler (@mh-hunters-main/server/main.lua:57)
> 
> this what i get for the hunters script

you ask this question by the wrong script 😅  
but it looks like that the id is not exsist when this happed, make a topic on mh-hunters for this to keep an overview cause it can help other people aswell 😅

**Comment by PanchoDaGoat** [comment]
i got target to work i had to switch it out but the cars in the tr2 get stuck on the top when locked in

**Comment by MaDHouSe79** [comment]
The vehicles must lock when you add them on the trailer, if not the vehicles will fall of the trailer.
as you see in the video on my youtube channel, ut sute work like that.

**Comment by PanchoDaGoat** [comment]
everything works but after i drive the truck with vehicles and take them off i come back and the trailer is liked collided with the truck then i cant detach the trailer

**Comment by MaDHouSe79** [comment]
i need more info on this issue, cause this i can't do much with this little info..

If you can show this in a video then I will see what happens.
