### ISSUE TITLE
third eye

### ISSUE THREAD

**Issue by poolshark120502** [MaDHouSe79/mh-trailers#3]
pls add support for ox_target

**Comment by poolshark120502** [comment]
![image](https://github.com/MaDHouSe79/mh-trailers/assets/72841575/53b2ff09-2026-47ad-aa89-9b47912b41a5)

**Comment by MaDHouSe79** [comment]
i just update it so you can use ox_target.

**Comment by poolshark120502** [comment]
thx i think its qbx ready now almost

**Comment by poolshark120502** [comment]
the shop for rental is using qb input can i ox lib

**Comment by MaDHouSe79** [comment]
i update the code, also its now support for qb and esx framework ox_lib menu's and ox_target.

**Comment by MaDHouSe79** [comment]
you need ox_lib for this menu, or load the script after ox_lib and ox_lib must loaded before the framework qbx.

**Comment by poolshark120502** [comment]
![image](https://github.com/MaDHouSe79/mh-trailers/assets/72841575/e7f1b5bb-6a9b-4918-a201-909c61ed2f73)
ox_lib is first start before core adn your trailer resource...

**Comment by MaDHouSe79** [comment]
check the fxmanifest.lua and take the stuff you need.

```conf
shared_scripts {
    --'@es_extended/imports.lua',   -- only if you use esx framework
    --'@ox_lib/init.lua',           -- only if you use ex_lib
    '@qb-core/shared/vehicles.lua', -- only if you use qb framework
    'core/mconfig.lua',
    'core/locale.lua',
    'locales/*.lua',
    'config.lua',
}
```

**Comment by MaDHouSe79** [comment]
I just update the code, check if this works for you.

**Comment by poolshark120502** [comment]
![image](https://github.com/MaDHouSe79/mh-trailers/assets/72841575/94325e83-8bd3-463e-ab1a-8ba6b3146344)
![image](https://github.com/MaDHouSe79/mh-trailers/assets/72841575/d99b3ff2-e1f7-45cc-97d3-e3997fa4f31b)

**Comment by MaDHouSe79** [comment]
if you use esx you must edit fxmanifest.lua to your server needs.

**Comment by MaDHouSe79** [comment]
![Schermafbeelding 2024-02-25 144241](https://github.com/MaDHouSe79/mh-trailers/assets/15558440/c72f925f-99eb-40ec-9dc4-b81e37d206fd)
And you need to load the scripts in order like this picture.

**Comment by poolshark120502** [comment]
![image](https://github.com/MaDHouSe79/mh-trailers/assets/72841575/ef96aea5-e627-44ff-9942-0c39ce3b21a2)

that error went away now im getting

**Comment by MaDHouSe79** [comment]
> ![image](https://private-user-images.githubusercontent.com/72841575/307629680-ef96aea5-e627-44ff-9942-0c39ce3b21a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5MDQ0MDUsIm5iZiI6MTcwODkwNDEwNSwicGF0aCI6Ii83Mjg0MTU3NS8zMDc2Mjk2ODAtZWY5NmFlYTUtZTYyNy00NGZmLTk5NDItMGMzOWNlM2IyMWEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI1VDIzMzUwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyOGJhYTFlMDJhODljYmY0Njc4Yjc4YTRiMjllNDZhNjBmN2JhYTI5MjFiZjVhNWFlNTUyYzIyZDQ1ZTNlNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HAw9eifkzvEtj786U0KFwEvXVo9MRuZEDa4oXCmJH28)
> 
> that error went away now im getting

if you use esx you must edit fxmanifest.lua to your server needs.

From
```lua
shared_scripts {
    --'@es_extended/imports.lua', -- only if you use esx framework
    --'@ox_lib/init.lua',         -- only if you use ex_lib
    'core/mconfig.lua',
    'core/locale.lua',
    'core/vehicles.lua',
    'locales/*.lua',
    'config.lua',
}
```

to
```lua
shared_scripts {
    '@es_extended/imports.lua', -- only if you use esx framework
    '@ox_lib/init.lua',         -- only if you use ex_lib
    'core/mconfig.lua',
    'core/locale.lua',
    'core/vehicles.lua',
    'locales/*.lua',
    'config.lua',
}
```

**Comment by poolshark120502** [comment]
no dont use esx im qbx remeber..

**Comment by MaDHouSe79** [comment]
you need '@ox_lib/init.lua' right?, so you need to edit your `fxmanifest.lua` so you can use it..

**Comment by poolshark120502** [comment]
omg man im so sorry for even bothering you on that i was thinking it so many times to but i saw "only if you use ex_lib" and i dont i use oxim just to stressed bc i be working on shit but then players came in and be like can you do this and that anywasy thank you so much brotha! <3
