### ISSUE TITLE
mh-trailers not working qbcore

### ISSUE THREAD

**Issue by jn1001** [MaDHouSe79/mh-trailers#6]
Hello I wanted to use youre script but had a few issues.

The script isnt working with qb-target. Also with ox_target its partially not working the shop throws errors nil global lib.

Also there is Config.Target and Config.Menu missing in Config.lua.

Thats all I could find sofar.

**Comment by tom091291** [comment]
check my pr fix so far is in there for qbcore

**Comment by jn1001** [comment]
Our server runs ox_lib as a dependencie for other ressources but we dont run ox_target. Thats why it probably isnt working.

**Comment by MaDHouSe79** [comment]
try a new one the code is updated 😅

**Comment by jn1001** [comment]
![grafik](https://github.com/MaDHouSe79/mh-trailers/assets/161364607/d079774e-cb38-48dd-b329-92923df31856)

**Comment by MaDHouSe79** [comment]
change in `core/mconfig.lua` this

From
```lua
if GetResourceState("ox_lib") ~= 'missing' then
    Config.Target = "ox_target" -- qb-target or ox_target
    Config.Menu = "ox_lib"      -- qb-input or ox_lib
elseif GetResourceState("ox_lib") == 'missing' then
    Config.Target = "qb-target" -- qb-target or ox_target
    Config.Menu = "qb-input"    -- qb-input or ox_lib
end
```
To
```lua
if GetResourceState("ox_lib") ~= 'missing' then
    Config.Target = "qb-target" -- qb-target or ox_target
    Config.Menu = "ox_lib"      -- qb-input or ox_lib
elseif GetResourceState("ox_lib") == 'missing' then
    Config.Target = "qb-target" -- qb-target or ox_target
    Config.Menu = "qb-input"    -- qb-input or ox_lib
end
```
cause you use ox_lib and no ox_target right?

**Comment by poolshark120502** [comment]
> I have tried it now multiple times but I cant third eye the shop ped if I use ox_lib with qb-target.

switch off to qbx

**Comment by jn1001** [comment]
> > I have tried it now multiple times but I cant third eye the shop ped if I use ox_lib with qb-target.
> 
> switch off to qbx

Hi, what do you mean exactly with switch off to qbx?

**Comment by jn1001** [comment]
I updated and now the qb-target works I can rent a truck. It takes the money and spawns only the truck without a trailer and I cant enter even the spawned truck its locked.

**Comment by MaDHouSe79** [comment]
> I updated and now the qb-target with qb-input works I can rent a truck. It takes the money and spawns only the truck without a trailer and I cant enter even the spawned truck its locked.
> 
> Also people can keep renting trucks and keep spawning new ones in and create chaos.

Ok i just fix that, hope this works for you.

**Comment by jn1001** [comment]
![grafik](https://github.com/MaDHouSe79/mh-trailers/assets/161364607/dd5291f0-1492-4212-b810-01d456c46265)

I updated but its the same menu works spawns the truck only takes money and truck is locked. Trailer doesnt spawn and this is the console output. And I can keep spawning trucks still.

**Comment by MaDHouSe79** [comment]
what are you doing? are you just download it and load it in the server? you don't look to any config file? fuel of something?
cause this is in the mconfig.lua.

**Comment by jn1001** [comment]
I forgot this time the fuel config. But the script still doesnt take money from you if you have 0 cash and still lets you rent a truck without paying anything. Also I get a notification that I got the keys to the vehicle but if I get out and try to enter again I dont have them. Also while sitting in the truck I cant lock or unlock doors.

**Comment by MaDHouSe79** [comment]
> I forgot this time the fuel config. But the script still doesnt take money from you if you have 0 cash and still lets you rent a truck without paying anything. Also I get a notification that I got the keys to the vehicle but if I get out and try to enter again I dont have them. Also while sitting in the truck I cant lock or unlock doors.

try if it works now with the money, cause i change stuff and you have to need to look inside mconfig.lua if the key does not work.

**Comment by jn1001** [comment]
The money issue is fixed. 

We use qb-vehiclekeys and I changed it in the config to this:
-- Vehiclekeys trigger
Config.UseServerTrigger = true
Config.ServerVehicleKeyTrigger = "qb-vehiclekeys:server:AcquireVehicleKeys"

Config.UseClientTrigger = false
Config.ClientVehicleKeyTrigger = "vehiclekeys:client:SetOwner"

I tried both and with both I dont get a key.

**Comment by MaDHouSe79** [comment]
> The money issue is fixed.
> 
> We use qb-vehiclekeys and I changed it in the config to this: -- Vehiclekeys trigger Config.UseServerTrigger = true Config.ServerVehicleKeyTrigger = "qb-vehiclekeys:server:AcquireVehicleKeys"
> 
> Config.UseClientTrigger = false Config.ClientVehicleKeyTrigger = "vehiclekeys:client:SetOwner"
> 
> I tried both and with both I dont get a key.

it sute work now

**Comment by jn1001** [comment]
You mean you updated again or the way its set up should work?

**Comment by MaDHouSe79** [comment]
you need to download again and setup it for your server, but the keys sute work now, i just test it and it works.

**Comment by poolshark120502** [comment]
can you add options for qbx vehicle keys ?

**Comment by MaDHouSe79** [comment]
> can you add options for qbx vehicle keys ?

https://github.com/MaDHouSe79/mh-trailers/blob/28f83410fc78f798c4500726c3f27877a65e926d/core/mconfig.lua#L41
